= Guillotine library

Guillotine library exposes the read-only part of the Enonic Content API, 
including access to the Enonic query language. 
Guillotine dynamically analyzes all available content types in applications and 
generates a GraphQL API specific to your site. 
This gives you direct, typed and documented access to all content within the site. 
Including the ability to follow references, child items and access media directly.

== Compatibility

[cols="1,1,3", options="header"]
|===
|Version
|XP Version
|Dependency

|4.1.0
|7.0.0
|com.enonic.lib:lib-guillotine:4.1.0

|4.0.0
|7.0.0
|com.enonic.lib:lib-guillotine:4.0.0

|3.0.0
|7.0.0
|com.enonic.lib:lib-guillotine:3.0.0

|2.0.0
|7.0.0
|com.enonic.lib:lib-guillotine:2.0.0

|1.0.1
|6.10.x
|com.enonic.lib:lib-guillotine:1.0.1

|1.0.0
|6.10.x
|com.enonic.lib:lib-guillotine:1.0.0
|===

== Breaking changes

=== Breaking changes in 4.0

- Type "Content": Field "page": Removed (Use fields "pageAsJson" or "components" instead)
- Types "Flat*Component*": Renamed to "*Component*".
- Type "FlatDescriptorBasedComponentData": Split into 2 types: "LayoutComponentData" and "PartComponentData"
- Fields "config": Renamed to "configAsJson"
- Type "Content": Field "components": By default, the components of the page template are used instead if there is one.
- Type "Content": Field "components": By default, the fragments are inlined

=== Breaking changes in 3.0

- Type "Content": Fields "creator", "modifier", "owner" and "permissions" need one of the following roles: "cms.cm.app", "cms.admin" or "system.admin"

=== Breaking changes in 2.0

- Type "PrincipalKey": Field "userStore" renamed to "idProvider"
- Type "Component": Field "controller" renamed to "descriptor"
- Type "Component": Field "name" removed

== Build

To build this project, execute the following:

[source,bash]
----
./gradlew clean build
----

== https://github.com/enonic/app-guillotine/tree/master/docs/index.adoc[Documentation]

