:imagesdir: ..

= Low level API

This section describes the various functions available for mounting and configuring the Guillotine library into your Enonic application.

== Functions

=== createSchema

The `createSchema(options)` function creates the GraphQL schema with custom options.

.Schema options
|===
|Name | Description

|applications: String or Array.<String>
|List of application keys for which GraphQL objects will be generated from content types. By default current application. Property is optional.

|allowPaths:String or Array.<String>
|Allowed content paths in addition to this site in the default mode. In the site-less mode will be used only provided `allowPaths`. Property is optional.

|subscriptionEventTypes:String or Array.<String>
|Specifies event type patterns to be listened by GraphQL Subscription. Property is optional. By default will be listened `node.*` events.
|===

.Example of creation schema
[source,javascript]
----
const guillotineLib = require('/lib/guillotine');

const SCHEMA = guillotineLib.createSchema({
    applications: ['com.enonic.app.hmdb', app.name],
    subscriptionEventTypes: ['myapp.eventName', 'node.*']
});
----

=== createHeadlessCmsType
The `createHeadlessCmsType(context)` function creates the Guillotine <<../api#_headlesscms, Headless CMS>> type.

.Example of usage
[source,javascript]
----
const guillotineLib = require('/lib/guillotine');

function createRootQueryType(context) {
    return context.schemaGenerator.createObjectType({
        name: 'Query',
        fields: {
            guillotine: {
                type: guillotineLib.createHeadlessCmsType(context),
                resolve: function () {
                    return {};
                }
            }
        }
    });
}
----

=== createContext
The `createContext(options)` function creates the context necessary to create Guillotine types.

Context options contains the same list options which are used for <<createSchema,schema options>> and can be extended by custom options.

An instance of `context` object exposes the following functions:

|===
|Name | Description

|addDictionaryType(obj: GraphQLObject): void
|Adds GraphQL object to dictionary. Each content type which implements any interface must be added to dictionary to define its implementations.

|putContentTypeType(name: string, obj: GraphQLObject): void
|Collects GraphQL object in map to quick access to it.

|uniqueName:String or Array.<String>
|Generates unique name for object type, if type with provided name already exists then to the end of the name will be added `_<count>`, where `count` is number of type with provided name.

|getOption(name: string): Object
|Returns option by name.

|putOption(name: string, value: object): void
|Adds a new option to context.
|===

.Example of usage
[source,javascript]
----
const guillotineLib = require('/lib/guillotine');

const context = guillotineLib.createContext();
----

=== execute

image:images/v-500.svg[Since version,opts=inline] The `execute(params)` function allows to execute a GraphQL query.

List of properties for `params` object:

|===
|Name | Description | Default value

|query:String
|GraphQL query. Property is required.
|

|variables:Object
|Variables for GraphQL query. Property is optional.
|

|siteId:String
|Site ID. Property is optional.
|ID of a current site.

|branch:String
|Branch. Property is optional.
|Branch from request.

|schema:GraphQLSchema
|GraphQL schema. Property is optional.
|

|schemaOptions:Object
|SchemaOptions object to customize schema. Property is optional.
|

|context:Object
|GraphQL context. Accessible in resolve function via `env.context`. Property is optional.
|
|===

List of properties for `schemaOptions` object:

|===
|Name | Description

|applications: String or Array.<String>
|Allowed application keys in addition to this site. Property is optional.

|allowPaths:String or Array.<String>
|Allowed content paths in addition to this site. Property is optional.

|subscriptionEventTypes:String or Array.<String>
|Specifies event type patterns to be listened by GraphQL Subscription. Property is optional.
|===

If the `schema` parameter is not provided to the function, then a schema will be created for each branch (`draft` or `master`) of the site which will be automatically updated when the any application is added/removed/re-deployed to the site.
The developer is responsible for implementation of the update of the schemas created outside of this function.
This function can not be used in site-less mode which is supported from version `5.6.0`, use `graphqlLib.execute` instead.


.Basic usage
[source,javascript]
----
const guillotineLib = require('/lib/guillotine');

exports.post = function (req) {
    let input = JSON.parse(req.body);

    let params = {
        query: input.query,
        variables: input.variables
    };

    return {
        contentType: 'application/json',
        body: guillotineLib.execute(params)
    };
};
----

.Usage with schema options
[source,javascript]
----
const guillotineLib = require('/lib/guillotine');
const contentLib = require('/lib/xp/content');
const contextLib = require('/lib/xp/context');
const portalLib = require('/lib/xp/portal');

exports.post = function (req) {
    let siteConfig = contextLib.run({
        branch: req.branch
    }, () => contentLib.getSiteConfig({
        key: portalLib.getSite()._id,
        applicationKey: 'com.enonic.app.guillotine'
    }));

    let input = JSON.parse(req.body);

    let params = {
        query: input.query,
        variables: input.variables,
        schemaOptions: {
            applications: siteConfig.applications,
            allowPaths: siteConfig.allowPaths,
            subscriptionEventTypes: siteConfig.subscriptionEventTypes
        }
    };

    return {
        contentType: 'application/json',
        body: guillotineLib.execute(params)
    };
};
----

.Customized schema
[source,javascript]
----
const guillotineLib = require('/lib/guillotine');

const SCHEMA = guillotineLib.createSchema();

exports.post = function (req) {
    let input = JSON.parse(req.body);

    let params = {
        query: input.query,
        variables: input.variables,
        schema: SCHEMA
    };

    return {
        contentType: 'application/json',
        body: guillotineLib.execute(params)
    };
};
----

=== initWebSockets

image:images/v-500.svg[Since version,opts=inline] The `initWebSockets(schema)` function is used to use default handling of `Subscription` via WebSocket. Only `node.*` events are listened to by default for current site, branch and repository. To customize which events must be listened use `subscriptionEventTypes` option during schema creation. This function is not supported in site-less mode, the
developer is responsible for implementing this functionality if needed.

.Schema options
|===
|Name | Description

|schema: GraphQLSchema
|GraphQL schema. This parameter must be provided if `schema` was created not using `execute` function. Property is optional.
|===

To start handle a WebSocket event XP provides the handler named https://developer.enonic.com/docs/xp/stable/framework/websocket[webSocketEvent], which will be called for every WebSocket event from client.

.Example of usage
[source,javascript]
----
const guillotineLib = require('/lib/guillotine');

const SCHEMA = guillotineLib.createSchema();

exports.webSocketEvent = guillotineLib.initWebSockets(SCHEMA);
----

=== createWebSocketData

image:images/v-500.svg[Since version,opts=inline] Creates WebSocket data object from request with `branch`, `repositoryId` and `site` properties. In site-less mode which is supported from version `5.6.0`, this function is not supported.
The developer is responsible for implementing this functionality if needed.

[source,javascript]
----
const guillotineLib = require('/lib/guillotine');

webSocket: {
    data: guillotineLib.createWebSocketData(req),
    subProtocols: ['graphql-ws']
}
----
