= Guillotine GraphQL API

At the root of the default Guillotine schema is a type `Query` with a field `guillotine` of type `HeadlessCms`.
The `HeadlessCms` type gathers fields allowing to retrieve contents or related data.

== Content

The type `Content` is an interface with multiple implementations generated from built-in content types but also from content types defined by your application.
All types implementing `Content` share the same fields at the exception of the field `data` defined for each implementation type.

== Relations

Multiple relations are generated to allow to navigate between contents.
By default, each content has the following relations:

* parent: Link to the parent content 
* children: Link to the child contents
* site: Link to the nearest site content

Moreover, every ContentSelector, MediaUploader, AttachmentUploader or ImageSelector defined in your content type form will 
be converted to a link to the related content(s).

=== Example: Children 

Query example: Retrieve the display name of the current content and the display name of its direct children

----
{
  guillotine {
    get {
      displayName
      children {
        displayName
      }
    }
  }
}
----

=== Example: ContentSelector

Query example: Retrieve the blog posts. For each post, return its display name and the display name of the related author

----
{
  guillotine {
    query(contentTypes:"com.enonic.app.myapp:post") {
      displayName
      ... on com_enonic_app_myapp_Post {
        data {          
          author {
            displayName
          }
        }
      }
    }
  }
}
----

== Image

Enonic XP can edit images at runtime.
Guillotine uses this functionality by generating, on every image, a field "imageUrl" generating a URL pointing to the processed image.

=== Example: Scaled Image URL

Query example: Retrieve the image contents and generate absolute URLs to these images cropped to 800x200px

----
{
  guillotine {
    query(contentTypes:"media:image") {
      displayName
      ... on media_Image {
        imageUrl(scale:"block(800,200)",type:absolute)
      }
    }
  }
}
----

== HTML

HTML fields are generated with a parameter "processHtml" allowing to replace abstract internal links by generated URLs. 

=== Example: Process HTML

Query example: Retrieve the Superhero blog posts. For each post, return its author display name, tags and processed content.

----
{
  guillotine {
    query(contentTypes:"com.enonic.app.myapp:post") {
      ... on com_enonic_app_myapp_Post {
        data {
          author {
            displayName
          }
          tags
          post(processHtml:{type:absolute})
        }
      }
    }
  }
}
----

== Static GraphQL types

The documentation, linked below, lists and describes all static GraphQL types generated by Guillotine

link:static.html[Static GraphQL types documentation]