= Guillotine library - Documentation

Guillotine library exposes the read-only part of the Enonic Content API, 
including access to the Enonic query language. 
Guillotine dynamically analyzes all available content types in the site and 
generates a GraphQL API specific to your site. 
This gives you direct, typed and documented access to all content within the site. 
Including the ability to follow references, child items and access media directly.

== Usage

=== Include the library

To include the library in your Enonic XP application, 
you will first need to add the Enonic repository to the repository list:

[source,gradle]
----
repositories {
    maven {
        url 'http://repo.enonic.com/public'
    }
}
----

Then add the following dependency (where `<version>` is the actual version to use):

[source,gradle]
----
dependencies {
    include 'com.enonic.lib:lib-sql:<version>'
}
----

=== API

The library proposes two solutions:
. Generate the entire GraphQL schema with possibilities to modify and extend it.
. Generate the Headless CMS Graph type to include

TODO

== Examples

=== Example 1: Generate a service with the default guillotine schema

Create an Enonic XP service file (example: /services/graphql/graphql.js) with the following code:
./services/graphql/graphql.js
[source,javascript]
----
var guillotineLib = require('/lib/guillotine');
var graphQlLib = require('/lib/graphql');

var schema;
exports.post = function (req) {
    schema = schema || guillotineLib.createSchema();
    var body = JSON.parse(req.body);
    var result = graphQlLib.execute(schema, body.query, body.variables);
    return {
        contentType: 'application/json',
        body: result
    };
};
----

You now have a 

