= Headless CMS for Enonic XP - Project Guillotine

Get instant access to XP's Content API and query language with GraphQL

NOTE: *Get your hands dirty!* Check out the https://developer.enonic.com/templates/headless-cms[Headless CMS starter] for the fastest hands on introduction to Headless CMS and Enonic XP.

== Introduction
Project Guillotine extends Enonic XP's existing CMS capabilities by exposing it through a GraphQL API.

Guillotine builds on the following components:

* https://developer.enonic.com/docs/xp[Enonic XP] - The core platform
** Content API - CMS core embedded in Enonic XP
** Site engine - Delivery engine for Guillotine
* https://developer.enonic.com/docs/content-studio[Content Studio] - CMS Authoring interface

== Why headless XP?

In addition to being a highly capable headless CMS, Enonic XP provides the following benefits:

* Bulk and cherry-pick publishing
* Mature and rich content modelling capabilities
* Developer appraised SDK that runs on a standalone computer
* Tree structures and document level access control
* Fully programmable and customisable preview
* Supports visual landing page authoring with typed components
* Dynamically generated and strongly typed API
* Real-time event streaming over websockets (GraphQL Subscriptions)
* API and access to it can be customized
* Developers are in full control of API versioning
* Hybrid - capable of acting as a traditional CMS as well
* Supports on premises deployment
* 100% Open Source

== Deployment

With a running instance of Enonic XP installed, you will need to deploy the API on the platform.

There are essentially two ways of deploying, as a standalone application, or by embedding Guillotine in your app.

Details on deployment

== Usage

Once installed, you get access to a range of capabilities, from running queries and following references to activating subscriptions.

Learn more about the <<api#,API>>, and <<usage#,how to use it>>.


== Advanced topics

By embedding Guillotine, you may take control over where it is deployed, who can access it and even customise the API. 

<<advanced#, Read more about extending and modifying the GraphQL API>>