= Guillotine - Go Headless with Enonic XP


The Guillotine project enables easy access to XP's Content API, including the ability to use the Enonic query language. 
Guillotine dynamically analyzes all available apps within a site, and dynamically generates a GraphQL API to access it. 

Essentially, this gives you direct access to all content within the site. Including the ability to follow references, 
child items and use both image services and access other media directly.

NOTE: For an optimal introduction to Guillotine. We recommend completing the https://developer.enonic.com/templates/headless-cms[Headless CMS starter] before you continue reading this documentation.


== Usage

There are essentially two ways of using Guillotine:

* Adding the Guillotine app to your site
* Adding the Guillotine library to your application

== Advanced

By including Guillotine as a <<library#,library in your application>>, you get full control over the exposed API. This enables you to both <<advanced#, extend and modify the GraphQL API>>, as well as controlling access to it and more.