= Guillotine Library 

This section describes how to add Guillotine to your application as a library.

== Step 1: Include the library
     
Add the following dependency (where `<version>` is the actual version of Guillotine you want to use):

[source,gradle]
----
dependencies {
  include 'com.enonic.lib:lib-guillotine:<version>'
}
----

== Step 2: Create a GraphQL endpoint
 
* Create an Enonic XP service file `/services/graphql/graphql.js` with the following content:
 
./services/graphql/graphql.js
[source,javascript]
----
var guillotineLib = require('/lib/guillotine'); // <1>
var graphQlLib = require('/lib/graphql'); // <1>

var schema = guillotineLib.createSchema(); // <2>

exports.post = function (req) { // <3>
 var body = JSON.parse(req.body); // <4>
 var result = graphQlLib.execute(schema, body.query, body.variables); // <5>
 return {
     contentType: 'application/json',
     body: JSON.stringify(result)
 };
};
----
<1> Requires the Guillotine and GraphQL libraries. 
The GraphQL library is already included with Guillotine and does not need to be added to your Gradle file
<2> Creates the GraphQL schema the first time the service is called. 
<3> Handles POST requests
<4> Parses the JSON body to retrieve the GraphQL query and variables
<5> Executes the query and variables against the schema created

You now have a GraphQL endpoint!
